# Generated by Django 5.1b1 on 2024-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of article')),
                ('anons', models.CharField(max_length=255, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='The article')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
